spring.application.name=undo_school
spring.datasource.url=jdbc:mysql://localhost:3306/undoschool
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
