name: Java CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: copy the orginal code
        uses: actions/checkout@v4
      - name: java setup
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: maven build
        run: mvn clean install -DskipTests